### ISSUE TITLE
Can initiate movement while alert dialog is open

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/OpenTemple#41]
Check tutorial for this. While the alert dialog for the giant rat is open, clicking into the game view will
already initiate movement and the hourglass will start draining, even though the player isn't moving.

**Comment by shartte** [comment]
Verified that this isn't a Vanilla issue. No interaction with the game view or UI is possible while an alert is open in Vanilla.

**Comment by DudeMcDude** [comment]
I think it was the animation clock locker?

**Comment by shartte** [comment]
I think you can't click any button (i.e. utility bar) when an alert is open in Vanilla.
OT currently doesn't care, heh. I'll have to check why that is.

**Comment by shartte** [comment]
Yeah, after checking, Vanilla just makes the alert windows as big as the screen is, and captures all events.
I made the window as big as the background image, so that explains it.

I think I'll introduce some sort of "modal" flag on windows that makes them redirect events to themselves...
