### ISSUE TITLE
Restore party selection after combat ends

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/OpenTemple#43]
Party selection should be restored when combat ends.

Symptom: Kill the giant rat in the tutorial, immediately try to loot its body and notice how no party-member is selected. Looting doesn't work until a party member is re-selected.

**Comment by shartte** [comment]
@DudeMcDude Do you know if this is a Vanilla thing? 
Or is clicking on a corpse going to auto-select the party leader?

I found it irritating that after the tutorial combat, if the giant rat went last, no one was selected after combat, and clicking the rat's corpse did nothing.

**Comment by DudeMcDude** [comment]
In what scenario does the rat go last? Dying of exertion?

**Comment by shartte** [comment]
The bug that caused it to get killed by AOO when it attacked :-D

**Comment by DudeMcDude** [comment]
Hehe
Well it's quite possible, the active char selection gets switched quite a bit.

**Comment by shartte** [comment]
Hm. I think we should just do the following:

After combat, if no party member is selected, select the party leader.

That seems sensible, even if Vanilla doesn't do it.

**Comment by DudeMcDude** [comment]
Fair enough.
I'd add a test for what happens when combat gets interrupted via dialog (using someone other than the leader to initiate convo).

**Comment by shartte** [comment]
Good point, does that even call TBEndCombat in that case? Hmmmmm

**Comment by DudeMcDude** [comment]
Yeah, via time event.
In Temple+ I changed this recently, hope I don't regret it hehe.
