### ISSUE TITLE
Focus Circle doesn't show on Tutorial Chest

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/OpenTemple#54]
In Vanilla:

![image](https://user-images.githubusercontent.com/1261399/133928035-43c93cd2-4be1-4431-af71-64a318615f41.png)

In OT:
![image](https://user-images.githubusercontent.com/1261399/133928038-d46b9760-b631-40d5-99bc-97f6d8b220b1.png)

Even OT can show the circles, but the mouse has to be moved after mouse-down to show them... Weird.

~~p.s.: Weirdly enough, it's unclear what determines that the circle shows. For Doors it doesn't seem to show in Vanilla either.~~

Same for doors, apparently, when mouse is held on top of door in Vanilla:
![image](https://user-images.githubusercontent.com/1261399/133928197-b48f864c-259a-41bc-89d2-973d578b3b4c.png)

**Comment by DudeMcDude** [comment]
This probably has to do with how the message loop is handled.

**Comment by shartte** [comment]
Hm, this might be slightly different handling for drag-selection between OT and Vanilla. Turns out, the circle comes from the object being considered part of the selection (during drag-select...). This might be considered a bug in vanilla since the chest (and neither the door) is selectable.

**Comment by DudeMcDude** [comment]
Oh, interesting... do these circles show for your chars?
I don't th8nk it's a bug though, e.g. in combat it shows a red circle and it's useful for confirming your target selection. Or does that hsppen on hover?

**Comment by shartte** [comment]
Crtitters have special rules. The function that decides whether the focus-ring should be shown is a hardcoded mess.
On simple mouse-over, contains etc. are usually exempt, unless they're part of the selection focus list.

I really don't think it's intended 😁

**Comment by DudeMcDude** [comment]
Gotcha. Then yeah, sounds like a bug.

**Comment by shartte** [comment]
BTW. this is also broken in TemplePlus :-D

I'll shelve this for now.

The real reason seems to be, if I am correct, that pressing the mouse on the game object sends one mouse message with flag=0x1 (LeftClick), but the object will only be added to the focus list if the message has 0x2 (LeftDown) set.
Since the mouse message generation in OT is based on T+, I probably inherited the bug.

**Comment by shartte** [comment]
A bit of reversing later: We reverse engineered the mouse code from windowed mode, I believe.
The full-screen DirectInput code is different. It will send a "LeftHeld" message (flag=0x2) after the button has been held for 250ms.
And I believe it will continue to send this message every frame thereafter. Interesting. I don't think we synthesize this message correctly in T+.

**Comment by DudeMcDude** [comment]
Yeah, looks that way.
But if I understand correctly, this bug also exists in vanilla windowed mode?
